
export default routes = Object.freeze({
  mainScreen: "MainScreen",
  openingScreen: "OpeningScreen",
  home: "Home",
  profile: "Profile",
  cart: "Cart",
  Products: "Products",
  allProducts: "AllProducts",
  details: "Details",
  Events: "Events",
  EventOnline: "EventOnline",
  EventOffline: "EventOffline",
  LoginScreen: "LoginScreen",
  IntroScreen: "IntroScreen",
  RegistrationScreen: "RegistrationScreen",
  ProductsScreen: "ProductsScreen",
  productBag: "productBag",
  AuctionScreen: "AuctionScreen",
  ProposalsScreen: "ProposalsScreen",
  addproduct: "Addproduct",
  addausproduct:"Addausproduct",
  editProduct:"EditProduct",
  addevent:"Addevent",
  onlinRoom:"onlineRoom"
});
